// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu7CJYMfpLK3c0k28UfnMB-5CTN6mM1Kc',
    appId: '1:127022021269:android:477e726988597bb02ab99c',
    messagingSenderId: '127022021269',
    projectId: 'green-leaf-project',
    storageBucket: 'green-leaf-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb7Yp3RZkb5VvDs42UhfwfUOsgPbCk6tw',
    appId: '1:127022021269:ios:c3b9d638a1f9e55d2ab99c',
    messagingSenderId: '127022021269',
    projectId: 'green-leaf-project',
    storageBucket: 'green-leaf-project.firebasestorage.app',
    iosBundleId: 'com.example.greenLeaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb7Yp3RZkb5VvDs42UhfwfUOsgPbCk6tw',
    appId: '1:127022021269:ios:c3b9d638a1f9e55d2ab99c',
    messagingSenderId: '127022021269',
    projectId: 'green-leaf-project',
    storageBucket: 'green-leaf-project.firebasestorage.app',
    iosBundleId: 'com.example.greenLeaf',
  );
}
